### ISSUE TITLE
N_EXT_PERF_COUNTERS

### ISSUE THREAD

**Issue by darbaria** [pulp-platform/zero-riscy#19]
Wonder what the correct value of parameter N_EXT_PERF_COUNTERS should be?

The current instance of it being set to 0
parameter N_EXT_PERF_COUNTERS = 0

followed by 

input  logic [N_EXT_PERF_COUNTERS-1:0] ext_perf_counters_i

doesn't make much sense.

**Comment by davideschiavone** [comment]
Yes 0 does not make so much sense, there should be an if statement that checks whether it is 0 or not.

**Comment by darbaria** [comment]
Okay I'll leave this to you to fix.
