### ISSUE TITLE
Testbench for running simulations

### ISSUE THREAD

**Issue by raulbehl** [pulp-platform/zero-riscy#21]
Hi, 

I was going through the source directory but couldn't find an existing Testbench which could be used to run sims. Is there a chance that the TB would also made open-source?

**Comment by FrancescoConti** [comment]
Hi, we don’t have exactly an open source standalone testbench for Zero-Riscy, but you can
- use PULPissimo as a simulation platform
- use PULPino as a simulation platform (but beware, the SW environment is legacy)
- slightly modify other testbenches. Here (https://github.com/pulp-platform/hwpe-tb) you find a testbench for accelerators which also includes a Zero-Riscy core and dummy memories

**Comment by raulbehl** [comment]
Thank you for the comment. I'll take a look at them. 

Closing!
