### ISSUE TITLE
ra register not update when single step debug

### ISSUE THREAD

**Issue by timdudu** [pulp-platform/zero-riscy#3]
When core execute JAL instruction, return address should be written to ra register. But in single step execution, the ra register is not updated.
Here is an example waveform. 
code is:  730000ef                jal     ra,102073c

1. the core is free run.
![capture](https://user-images.githubusercontent.com/29726453/36009162-f024b004-0d85-11e8-9dff-ab42104060bc.PNG)
You can see the return address 0x1020010 is written to ra register.

2. the core is in single step.
![image](https://user-images.githubusercontent.com/29726453/36009709-73b7f8f2-0d88-11e8-972f-acb143fa1ac7.png)
Return address 0x1020010 is not written to ra register.  We debug this issue and found that core deassert we_a_i in DBG_SIGNAL state. And ctrl_fsm_ns enter DBG_SIGNAL state before ra register update. 
I tried to fix this issue by add & id_ready_i when ctrl_fsm_ns try to enter DBG_SIGNAL.
              jump_set_i: begin
                pc_mux_o          = PC_JUMP;
                pc_set_o          = 1'b1;
                perf_jump_o       = 1'b1;
                dbg_trap_o        = dbg_settings_i[DBG_SETS_SSTE];
                if (dbg_req_i & id_ready_i)
                  ctrl_fsm_ns = DBG_SIGNAL;

The return address can be written to ra due to this change. But I'm not sure this is a good workaround.
![image](https://user-images.githubusercontent.com/29726453/36010048-49a919c2-0d8a-11e8-9b9f-31c48ece48c9.png)

**Comment by timdudu** [comment]
Sorry, it's ra register not la.

**Comment by davideschiavone** [comment]
Thanks a lot Tim,

I'll fix it asap and let you know soon.

Thanks a lot for reporting it ,
Davide

2018-02-09 4:16 GMT+01:00 timdudu <notifications@github.com>:

**Comment by davideschiavone** [comment]
Dear Tim, 

I fixed the bug, you can find the fix here: d4d46971ebd5e0a637d2d182af675e7c43078885

The solution is similar to the one you proposed but I simply removed the check of dbg request as it will be check in the second cycle of the instruction.

Thanks a lot,
Davide
