### ISSUE TITLE
clock_en_i no longer connected

### ISSUE THREAD

**Issue by adich0** [pulp-platform/zero-riscy#5]
Hello,

It seems that the top level signal 'clock_en_i' no longer drives anything. Is this intentional?

**Comment by davideschiavone** [comment]
Hello, 

yes in the master branch, zero-riscy has been adapted to work with the more recent platforms PULP and PULPissimo which have a different event unit than PULPino, and the core now handles its clock gate by itself without relying on external units. In the PULPino branch the clock enable is still driving logic.
